js:
  base:
    - bootstrap.min.js
    - jquery.easing.1.3.js
    - menu.js
    - jquery.slides.min.js
    - hogstock.js
css:
  base:
    - bootstrap.min.css
    - bootstrap-responsive.min.css
    - slideshow.css
    - hogstock.css 
    - menu.css
