js:
  vendor:
    - vendor/bootstrap.min.js
    - vendor/jquery.easing.1.3.js
    - vendor/menu.js
    
  base:
    - hogstock.js
css:
  vendor:
    - vendor/bootstrap.min.css
    - vendor/bootstrap-responsive.min.css
    - vendor/menu.css
    - vendor/vallenato.css
    - vendor/testimonials.css

  base:
    - hogstock.css 
