js:
  base:
    - bootstrap.min.js
    - jquery.cycle.js
    - jquery.easing.1.3.js
    - menu.js
    - rslides.min.js
    - hogstock.js
css:
  base:
    - bootstrap.min.css
    - bootstrap-responsive.min.css
    - rslides.css
    - hogstock.css 
    - menu.css
    - vallenato.css
    - testimonials.css
