sendgrid: 
  username: hogstock
  password: speedfreak1000
  emails: 'jakesorce@gmail.com'
  address: smtp.sendgrid.net
  port: 587
  domain: hogstock.com
  authentication: plain
  starttls_auto: true
